# Generated by Django 5.1.4 on 2024-12-05 04:53

from django.db import migrations


def seed_priority_and_status(apps, schema_editor):
    Priority = apps.get_model('tasks', 'Priority')
    Status = apps.get_model('tasks', 'Status')

    # Insertar valores en Priority
    Priority.objects.bulk_create([
        Priority(name='Low', level=1),
        Priority(name='Medium', level=2),
        Priority(name='High', level=3),
        Priority(name='Urgent', level=4),
    ])

    # Insertar valores en Status
    Status.objects.bulk_create([
        Status(status='To Do'),
        Status(status='In Progress'),
        Status(status='Past Due'),
        Status(status='On Hold'),
        Status(status='Awaiting Approval'),
        Status(status='Deferred'),
        Status(status='Canceled'),
        Status(status='Completed'),
        Status(status='Completed PD'),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_priority_and_status),
    ]
