# Generated by Django 5.1.3 on 2024-12-03 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_add_default_data'),
        ('tasks', '0003_add_default_data'),
    ]

    operations = [
    ]
